@startuml RouteMonitoring

[*] --> NOT_MONITORED: [1]
NOT_MONITORED -right-> MONITORED: [1] PointsMonitored && RouteSet && InverseTransitsInactive
MONITORED -left-> NOT_MONITORED: [1] !PointsMonitored || !RouteSet || !InverseTransitsInactive

NOT_MONITORED: State = ActiveInactive::INACTIVE
MONITORED: State = ActiveInactive::ACTIVE

@enduml
