@startuml RouteMonitoring

[*] --> NOT_CONTROLLED: [1]
NOT_CONTROLLED -right-> CONTROLLED: [1] PointsControlled && RouteSet && InverseTransitsInactive
CONTROLLED -left-> NOT_CONTROLLED: [1] !PointsControlled || !RouteSet || !InverseTransitsInactive

NOT_CONTROLLED: State = ActiveInactive::INACTIVE
CONTROLLED: State = ActiveInactive::ACTIVE

@enduml
