MACHINE Enums
SETS
  EulynxEndPosition = {EulynxEndPosition_LEFT, EulynxEndPosition_RIGHT, EulynxEndPosition_NO_END_POSITION, EulynxEndPosition_UNINTENDED};
  EulynxCommandedEndPosition = {EulynxCommandedEndPosition_NOT_COMMANDED, EulynxCommandedEndPosition_LEFT, EulynxCommandedEndPosition_RIGHT};
  OccupancyStatus = {OccupancyStatus_OCCUPIED, OccupancyStatus_VACANT};
  RouteState = {RouteState_SET, RouteState_PREPARING, RouteState_RELEASED};
  ActiveInactive = {ActiveInactive_INACTIVE, ActiveInactive_ACTIVE};
  PointState = {PointState_LEFT, PointState_RIGHT, PointState_UNDETERMINED};
  OpenCloseState = {OpenCloseState_OPEN, OpenCloseState_CLOSED}
END