MACHINE Enums
SETS
  E_EulynxEndPosition = {EulynxEndPosition_LEFT, EulynxEndPosition_RIGHT, EulynxEndPosition_NO_END_POSITION, EulynxEndPosition_UNINTENDED};
  E_EulynxCommandedEndPosition = {EulynxCommandedEndPosition_NOT_COMMANDED, EulynxCommandedEndPosition_LEFT, EulynxCommandedEndPosition_RIGHT};
  E_OccupancyStatus = {OccupancyStatus_OCCUPIED, OccupancyStatus_VACANT};
  E_RouteState = {RouteState_SET, RouteState_PREPARING, RouteState_RELEASED};
  E_ActiveInactive = {ActiveInactive_INACTIVE, ActiveInactive_ACTIVE};
  E_PointState = {PointState_LEFT, PointState_RIGHT, PointState_UNDETERMINED};
  E_OpenCloseState = {OpenCloseState_OPEN, OpenCloseState_CLOSED}
END