//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ExpressionParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IExpressionListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] ExpressionParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] ExpressionParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ExpressionParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ExpressionParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] ExpressionParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] ExpressionParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] ExpressionParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] ExpressionParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] ExpressionParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] ExpressionParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] ExpressionParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] ExpressionParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.timeoutExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimeoutExpr([NotNull] ExpressionParser.TimeoutExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.timeoutExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimeoutExpr([NotNull] ExpressionParser.TimeoutExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.quantifierExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantifierExpr([NotNull] ExpressionParser.QuantifierExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.quantifierExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantifierExpr([NotNull] ExpressionParser.QuantifierExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] ExpressionParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] ExpressionParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOp([NotNull] ExpressionParser.CompOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOp([NotNull] ExpressionParser.CompOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyName([NotNull] ExpressionParser.PropertyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyName([NotNull] ExpressionParser.PropertyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.graphOrInterfaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphOrInterfaceName([NotNull] ExpressionParser.GraphOrInterfaceNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.graphOrInterfaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphOrInterfaceName([NotNull] ExpressionParser.GraphOrInterfaceNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableName([NotNull] ExpressionParser.VariableNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableName([NotNull] ExpressionParser.VariableNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.quantifierVariableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantifierVariableName([NotNull] ExpressionParser.QuantifierVariableNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.quantifierVariableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantifierVariableName([NotNull] ExpressionParser.QuantifierVariableNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.refVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefVar([NotNull] ExpressionParser.RefVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.refVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefVar([NotNull] ExpressionParser.RefVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.valueReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueReference([NotNull] ExpressionParser.ValueReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.valueReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueReference([NotNull] ExpressionParser.ValueReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedName([NotNull] ExpressionParser.QualifiedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedName([NotNull] ExpressionParser.QualifiedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.durationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDurationLiteral([NotNull] ExpressionParser.DurationLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.durationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDurationLiteral([NotNull] ExpressionParser.DurationLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanLiteral([NotNull] ExpressionParser.BooleanLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanLiteral([NotNull] ExpressionParser.BooleanLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.noneLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoneLiteral([NotNull] ExpressionParser.NoneLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.noneLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoneLiteral([NotNull] ExpressionParser.NoneLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.enumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationTypeName([NotNull] ExpressionParser.EnumerationTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.enumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationTypeName([NotNull] ExpressionParser.EnumerationTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.enumerationLiteralName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationLiteralName([NotNull] ExpressionParser.EnumerationLiteralNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.enumerationLiteralName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationLiteralName([NotNull] ExpressionParser.EnumerationLiteralNameContext context);
}
