//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ExpressionParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IExpressionVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] ExpressionParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] ExpressionParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] ExpressionParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] ExpressionParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] ExpressionParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] ExpressionParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.timeoutExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeoutExpression([NotNull] ExpressionParser.TimeoutExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.quantifierExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantifierExpression([NotNull] ExpressionParser.QuantifierExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] ExpressionParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOp([NotNull] ExpressionParser.CompOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyName([NotNull] ExpressionParser.PropertyNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.graphOrInterfaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraphOrInterfaceName([NotNull] ExpressionParser.GraphOrInterfaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableName([NotNull] ExpressionParser.VariableNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.quantifierVariableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantifierVariableName([NotNull] ExpressionParser.QuantifierVariableNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableReference([NotNull] ExpressionParser.VariableReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.valueReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueReference([NotNull] ExpressionParser.ValueReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] ExpressionParser.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.durationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDurationLiteral([NotNull] ExpressionParser.DurationLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] ExpressionParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.noneLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoneLiteral([NotNull] ExpressionParser.NoneLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.enumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationTypeName([NotNull] ExpressionParser.EnumerationTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExpressionParser.enumerationLiteralName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationLiteralName([NotNull] ExpressionParser.EnumerationLiteralNameContext context);
}
