//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class ExpressionLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		AND=10, OR=11, NOT=12, EQUAL=13, NOTEQUAL=14, LBRACK=15, RBRACK=16, DOT=17, 
		DCOLON=18, AT=19, NOW=20, MILLISECONDS=21, GTE=22, PLUS=23, NAME_ALL_LOWERCASE=24, 
		NAME_ALL_UPPERCASE=25, NAME_LOWER_SNAKE_CASE=26, NAME_CAMEL_CASE=27, NAME_UPPER_SNAKE_CASE=28, 
		NAME_PASCAL_CASE=29, NUMBER=30, ASSIGN=31, PUMLNEWLINE=32, WS=33;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"AND", "OR", "NOT", "EQUAL", "NOTEQUAL", "LBRACK", "RBRACK", "DOT", "DCOLON", 
		"AT", "NOW", "MILLISECONDS", "GTE", "PLUS", "NAME_ALL_LOWERCASE", "NAME_ALL_UPPERCASE", 
		"NAME_LOWER_SNAKE_CASE", "NAME_CAMEL_CASE", "NAME_UPPER_SNAKE_CASE", "NAME_PASCAL_CASE", 
		"NUMBER", "ASSIGN", "PUMLNEWLINE", "WS"
	};


	public ExpressionLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ExpressionLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'Any'", "'All'", "'in'", "'|'", "'true'", "'false'", 
		"'None'", "'&&'", "'||'", "'!'", "'=='", "'!='", "'['", "']'", "'.'", 
		"'::'", "'@'", "'now'", "'ms'", "'>='", "'+'", null, null, null, null, 
		null, null, null, "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "AND", "OR", 
		"NOT", "EQUAL", "NOTEQUAL", "LBRACK", "RBRACK", "DOT", "DCOLON", "AT", 
		"NOW", "MILLISECONDS", "GTE", "PLUS", "NAME_ALL_LOWERCASE", "NAME_ALL_UPPERCASE", 
		"NAME_LOWER_SNAKE_CASE", "NAME_CAMEL_CASE", "NAME_UPPER_SNAKE_CASE", "NAME_PASCAL_CASE", 
		"NUMBER", "ASSIGN", "PUMLNEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Expression.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ExpressionLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,33,198,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,
		7,28,2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,1,0,1,0,1,1,1,1,1,2,1,2,1,
		2,1,2,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,7,1,7,
		1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,10,1,10,1,10,1,11,1,
		11,1,12,1,12,1,12,1,13,1,13,1,13,1,14,1,14,1,15,1,15,1,16,1,16,1,17,1,
		17,1,17,1,18,1,18,1,19,1,19,1,19,1,19,1,20,1,20,1,20,1,21,1,21,1,21,1,
		22,1,22,1,23,1,23,5,23,140,8,23,10,23,12,23,143,9,23,1,24,1,24,5,24,147,
		8,24,10,24,12,24,150,9,24,1,25,1,25,5,25,154,8,25,10,25,12,25,157,9,25,
		1,26,1,26,5,26,161,8,26,10,26,12,26,164,9,26,1,27,1,27,5,27,168,8,27,10,
		27,12,27,171,9,27,1,28,1,28,5,28,175,8,28,10,28,12,28,178,9,28,1,29,4,
		29,181,8,29,11,29,12,29,182,1,30,1,30,1,31,1,31,1,31,1,31,1,31,1,32,4,
		32,193,8,32,11,32,12,32,194,1,32,1,32,0,0,33,1,1,3,2,5,3,7,4,9,5,11,6,
		13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,14,29,15,31,16,33,17,35,18,37,
		19,39,20,41,21,43,22,45,23,47,24,49,25,51,26,53,27,55,28,57,29,59,30,61,
		31,63,32,65,33,1,0,9,1,0,97,122,2,0,48,57,97,122,1,0,65,90,2,0,48,57,65,
		90,3,0,48,57,95,95,97,122,3,0,48,57,65,90,97,122,3,0,48,57,65,90,95,95,
		1,0,48,57,3,0,9,10,13,13,32,32,205,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,
		0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,
		0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,0,27,1,0,0,0,
		0,29,1,0,0,0,0,31,1,0,0,0,0,33,1,0,0,0,0,35,1,0,0,0,0,37,1,0,0,0,0,39,
		1,0,0,0,0,41,1,0,0,0,0,43,1,0,0,0,0,45,1,0,0,0,0,47,1,0,0,0,0,49,1,0,0,
		0,0,51,1,0,0,0,0,53,1,0,0,0,0,55,1,0,0,0,0,57,1,0,0,0,0,59,1,0,0,0,0,61,
		1,0,0,0,0,63,1,0,0,0,0,65,1,0,0,0,1,67,1,0,0,0,3,69,1,0,0,0,5,71,1,0,0,
		0,7,75,1,0,0,0,9,79,1,0,0,0,11,82,1,0,0,0,13,84,1,0,0,0,15,89,1,0,0,0,
		17,95,1,0,0,0,19,100,1,0,0,0,21,103,1,0,0,0,23,106,1,0,0,0,25,108,1,0,
		0,0,27,111,1,0,0,0,29,114,1,0,0,0,31,116,1,0,0,0,33,118,1,0,0,0,35,120,
		1,0,0,0,37,123,1,0,0,0,39,125,1,0,0,0,41,129,1,0,0,0,43,132,1,0,0,0,45,
		135,1,0,0,0,47,137,1,0,0,0,49,144,1,0,0,0,51,151,1,0,0,0,53,158,1,0,0,
		0,55,165,1,0,0,0,57,172,1,0,0,0,59,180,1,0,0,0,61,184,1,0,0,0,63,186,1,
		0,0,0,65,192,1,0,0,0,67,68,5,40,0,0,68,2,1,0,0,0,69,70,5,41,0,0,70,4,1,
		0,0,0,71,72,5,65,0,0,72,73,5,110,0,0,73,74,5,121,0,0,74,6,1,0,0,0,75,76,
		5,65,0,0,76,77,5,108,0,0,77,78,5,108,0,0,78,8,1,0,0,0,79,80,5,105,0,0,
		80,81,5,110,0,0,81,10,1,0,0,0,82,83,5,124,0,0,83,12,1,0,0,0,84,85,5,116,
		0,0,85,86,5,114,0,0,86,87,5,117,0,0,87,88,5,101,0,0,88,14,1,0,0,0,89,90,
		5,102,0,0,90,91,5,97,0,0,91,92,5,108,0,0,92,93,5,115,0,0,93,94,5,101,0,
		0,94,16,1,0,0,0,95,96,5,78,0,0,96,97,5,111,0,0,97,98,5,110,0,0,98,99,5,
		101,0,0,99,18,1,0,0,0,100,101,5,38,0,0,101,102,5,38,0,0,102,20,1,0,0,0,
		103,104,5,124,0,0,104,105,5,124,0,0,105,22,1,0,0,0,106,107,5,33,0,0,107,
		24,1,0,0,0,108,109,5,61,0,0,109,110,5,61,0,0,110,26,1,0,0,0,111,112,5,
		33,0,0,112,113,5,61,0,0,113,28,1,0,0,0,114,115,5,91,0,0,115,30,1,0,0,0,
		116,117,5,93,0,0,117,32,1,0,0,0,118,119,5,46,0,0,119,34,1,0,0,0,120,121,
		5,58,0,0,121,122,5,58,0,0,122,36,1,0,0,0,123,124,5,64,0,0,124,38,1,0,0,
		0,125,126,5,110,0,0,126,127,5,111,0,0,127,128,5,119,0,0,128,40,1,0,0,0,
		129,130,5,109,0,0,130,131,5,115,0,0,131,42,1,0,0,0,132,133,5,62,0,0,133,
		134,5,61,0,0,134,44,1,0,0,0,135,136,5,43,0,0,136,46,1,0,0,0,137,141,7,
		0,0,0,138,140,7,1,0,0,139,138,1,0,0,0,140,143,1,0,0,0,141,139,1,0,0,0,
		141,142,1,0,0,0,142,48,1,0,0,0,143,141,1,0,0,0,144,148,7,2,0,0,145,147,
		7,3,0,0,146,145,1,0,0,0,147,150,1,0,0,0,148,146,1,0,0,0,148,149,1,0,0,
		0,149,50,1,0,0,0,150,148,1,0,0,0,151,155,7,0,0,0,152,154,7,4,0,0,153,152,
		1,0,0,0,154,157,1,0,0,0,155,153,1,0,0,0,155,156,1,0,0,0,156,52,1,0,0,0,
		157,155,1,0,0,0,158,162,7,0,0,0,159,161,7,5,0,0,160,159,1,0,0,0,161,164,
		1,0,0,0,162,160,1,0,0,0,162,163,1,0,0,0,163,54,1,0,0,0,164,162,1,0,0,0,
		165,169,7,2,0,0,166,168,7,6,0,0,167,166,1,0,0,0,168,171,1,0,0,0,169,167,
		1,0,0,0,169,170,1,0,0,0,170,56,1,0,0,0,171,169,1,0,0,0,172,176,7,2,0,0,
		173,175,7,5,0,0,174,173,1,0,0,0,175,178,1,0,0,0,176,174,1,0,0,0,176,177,
		1,0,0,0,177,58,1,0,0,0,178,176,1,0,0,0,179,181,7,7,0,0,180,179,1,0,0,0,
		181,182,1,0,0,0,182,180,1,0,0,0,182,183,1,0,0,0,183,60,1,0,0,0,184,185,
		5,61,0,0,185,62,1,0,0,0,186,187,5,92,0,0,187,188,5,110,0,0,188,189,1,0,
		0,0,189,190,6,31,0,0,190,64,1,0,0,0,191,193,7,8,0,0,192,191,1,0,0,0,193,
		194,1,0,0,0,194,192,1,0,0,0,194,195,1,0,0,0,195,196,1,0,0,0,196,197,6,
		32,0,0,197,66,1,0,0,0,9,0,141,148,155,162,169,176,182,194,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
