//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Expression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IExpressionListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ExpressionBaseListener : IExpressionListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] ExpressionParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] ExpressionParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ExpressionParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ExpressionParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] ExpressionParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] ExpressionParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] ExpressionParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] ExpressionParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.notExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpr([NotNull] ExpressionParser.NotExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.notExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpr([NotNull] ExpressionParser.NotExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] ExpressionParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] ExpressionParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.timeoutExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimeoutExpr([NotNull] ExpressionParser.TimeoutExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.timeoutExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimeoutExpr([NotNull] ExpressionParser.TimeoutExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.quantifierExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantifierExpr([NotNull] ExpressionParser.QuantifierExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.quantifierExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantifierExpr([NotNull] ExpressionParser.QuantifierExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] ExpressionParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] ExpressionParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOp([NotNull] ExpressionParser.CompOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOp([NotNull] ExpressionParser.CompOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyName([NotNull] ExpressionParser.PropertyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyName([NotNull] ExpressionParser.PropertyNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.graphOrInterfaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphOrInterfaceName([NotNull] ExpressionParser.GraphOrInterfaceNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.graphOrInterfaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphOrInterfaceName([NotNull] ExpressionParser.GraphOrInterfaceNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableName([NotNull] ExpressionParser.VariableNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableName([NotNull] ExpressionParser.VariableNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.quantifierVariableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantifierVariableName([NotNull] ExpressionParser.QuantifierVariableNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.quantifierVariableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantifierVariableName([NotNull] ExpressionParser.QuantifierVariableNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.refVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefVar([NotNull] ExpressionParser.RefVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.refVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefVar([NotNull] ExpressionParser.RefVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.valueReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueReference([NotNull] ExpressionParser.ValueReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.valueReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueReference([NotNull] ExpressionParser.ValueReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] ExpressionParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] ExpressionParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.durationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDurationLiteral([NotNull] ExpressionParser.DurationLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.durationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDurationLiteral([NotNull] ExpressionParser.DurationLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteral([NotNull] ExpressionParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteral([NotNull] ExpressionParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.noneLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoneLiteral([NotNull] ExpressionParser.NoneLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.noneLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoneLiteral([NotNull] ExpressionParser.NoneLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.enumerationTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerationTypeName([NotNull] ExpressionParser.EnumerationTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.enumerationTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerationTypeName([NotNull] ExpressionParser.EnumerationTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.enumerationLiteralName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerationLiteralName([NotNull] ExpressionParser.EnumerationLiteralNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.enumerationLiteralName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerationLiteralName([NotNull] ExpressionParser.EnumerationLiteralNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
