//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Graph.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class GraphParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, STARTUML=11, ENDUML=12, ARROW=13, COLON=14, LBRACK=15, RBRACK=16, 
		LBRACE=17, RBRACE=18, INITIAL_STATE_NAME=19, INT=20, COMMENT=21, NEWLINE=22, 
		WS=23, PSEUDOSTATE=24, AND=25, OR=26, NOT=27, EQUAL=28, NOTEQUAL=29, DOT=30, 
		DCOLON=31, AT=32, NOW=33, MILLISECONDS=34, GTE=35, PLUS=36, NAME_ALL_LOWERCASE=37, 
		NAME_ALL_UPPERCASE=38, NAME_LOWER_SNAKE_CASE=39, NAME_CAMELCASE=40, NAME_UPPER_SNAKE_CASE=41, 
		NAME_PASCALCASE=42, NUMBER=43, ASSIGN=44, PUMLNEWLINE=45;
	public const int
		RULE_diagram = 0, RULE_diagramName = 1, RULE_diagramBody = 2, RULE_transition = 3, 
		RULE_stateDeclaration = 4, RULE_pseudostateDeclaration = 5, RULE_pseudostateName = 6, 
		RULE_stateReference = 7, RULE_stateName = 8, RULE_transitionLabel = 9, 
		RULE_priority = 10, RULE_labelText = 11, RULE_comment = 12, RULE_termReference = 13, 
		RULE_atom = 14, RULE_assignment = 15, RULE_expression = 16, RULE_orExpr = 17, 
		RULE_andExpr = 18, RULE_notExpr = 19, RULE_timeoutExpression = 20, RULE_quantifierExpression = 21, 
		RULE_comparison = 22, RULE_compOp = 23, RULE_propertyName = 24, RULE_graphOrInterfaceName = 25, 
		RULE_variableName = 26, RULE_quantifierVariableName = 27, RULE_variableReference = 28, 
		RULE_valueReference = 29, RULE_qualifiedName = 30, RULE_durationLiteral = 31, 
		RULE_booleanLiteral = 32, RULE_noneLiteral = 33, RULE_enumerationTypeName = 34, 
		RULE_enumerationLiteralName = 35;
	public static readonly string[] ruleNames = {
		"diagram", "diagramName", "diagramBody", "transition", "stateDeclaration", 
		"pseudostateDeclaration", "pseudostateName", "stateReference", "stateName", 
		"transitionLabel", "priority", "labelText", "comment", "termReference", 
		"atom", "assignment", "expression", "orExpr", "andExpr", "notExpr", "timeoutExpression", 
		"quantifierExpression", "comparison", "compOp", "propertyName", "graphOrInterfaceName", 
		"variableName", "quantifierVariableName", "variableReference", "valueReference", 
		"qualifiedName", "durationLiteral", "booleanLiteral", "noneLiteral", "enumerationTypeName", 
		"enumerationLiteralName"
	};

	private static readonly string[] _LiteralNames = {
		null, "'state'", "'('", "')'", "'Any'", "'All'", "'in'", "'|'", "'true'", 
		"'false'", "'None'", null, null, null, "':'", "'['", "']'", "'{'", "'}'", 
		"'[*]'", null, null, null, null, "'<<choice>>'", "'&&'", "'||'", "'!'", 
		"'=='", "'!='", "'.'", "'::'", "'@'", "'now'", "'ms'", "'>='", "'+'", 
		null, null, null, null, null, null, null, "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "STARTUML", 
		"ENDUML", "ARROW", "COLON", "LBRACK", "RBRACK", "LBRACE", "RBRACE", "INITIAL_STATE_NAME", 
		"INT", "COMMENT", "NEWLINE", "WS", "PSEUDOSTATE", "AND", "OR", "NOT", 
		"EQUAL", "NOTEQUAL", "DOT", "DCOLON", "AT", "NOW", "MILLISECONDS", "GTE", 
		"PLUS", "NAME_ALL_LOWERCASE", "NAME_ALL_UPPERCASE", "NAME_LOWER_SNAKE_CASE", 
		"NAME_CAMELCASE", "NAME_UPPER_SNAKE_CASE", "NAME_PASCALCASE", "NUMBER", 
		"ASSIGN", "PUMLNEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Graph.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static GraphParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GraphParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GraphParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class DiagramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STARTUML() { return GetToken(GraphParser.STARTUML, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DiagramBodyContext diagramBody() {
			return GetRuleContext<DiagramBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDUML() { return GetToken(GraphParser.ENDUML, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DiagramNameContext diagramName() {
			return GetRuleContext<DiagramNameContext>(0);
		}
		public DiagramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_diagram; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterDiagram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitDiagram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiagram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DiagramContext diagram() {
		DiagramContext _localctx = new DiagramContext(Context, State);
		EnterRule(_localctx, 0, RULE_diagram);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			Match(STARTUML);
			State = 74;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				{
				State = 73;
				diagramName();
				}
				break;
			}
			State = 76;
			diagramBody();
			State = 77;
			Match(ENDUML);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DiagramNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public GraphOrInterfaceNameContext graphOrInterfaceName() {
			return GetRuleContext<GraphOrInterfaceNameContext>(0);
		}
		public DiagramNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_diagramName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterDiagramName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitDiagramName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiagramName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DiagramNameContext diagramName() {
		DiagramNameContext _localctx = new DiagramNameContext(Context, State);
		EnterRule(_localctx, 2, RULE_diagramName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			graphOrInterfaceName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DiagramBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TransitionContext[] transition() {
			return GetRuleContexts<TransitionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TransitionContext transition(int i) {
			return GetRuleContext<TransitionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StateDeclarationContext[] stateDeclaration() {
			return GetRuleContexts<StateDeclarationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StateDeclarationContext stateDeclaration(int i) {
			return GetRuleContext<StateDeclarationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PseudostateDeclarationContext[] pseudostateDeclaration() {
			return GetRuleContexts<PseudostateDeclarationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PseudostateDeclarationContext pseudostateDeclaration(int i) {
			return GetRuleContext<PseudostateDeclarationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommentContext[] comment() {
			return GetRuleContexts<CommentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommentContext comment(int i) {
			return GetRuleContext<CommentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(GraphParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(GraphParser.NEWLINE, i);
		}
		public DiagramBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_diagramBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterDiagramBody(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitDiagramBody(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiagramBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DiagramBodyContext diagramBody() {
		DiagramBodyContext _localctx = new DiagramBodyContext(Context, State);
		EnterRule(_localctx, 4, RULE_diagramBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 3710858559490L) != 0)) {
				{
				State = 86;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
				case 1:
					{
					State = 81;
					transition();
					}
					break;
				case 2:
					{
					State = 82;
					stateDeclaration();
					}
					break;
				case 3:
					{
					State = 83;
					pseudostateDeclaration();
					}
					break;
				case 4:
					{
					State = 84;
					comment();
					}
					break;
				case 5:
					{
					State = 85;
					Match(NEWLINE);
					}
					break;
				}
				}
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TransitionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StateReferenceContext[] stateReference() {
			return GetRuleContexts<StateReferenceContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StateReferenceContext stateReference(int i) {
			return GetRuleContext<StateReferenceContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(GraphParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(GraphParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(GraphParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TransitionLabelContext transitionLabel() {
			return GetRuleContext<TransitionLabelContext>(0);
		}
		public TransitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_transition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterTransition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitTransition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTransition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TransitionContext transition() {
		TransitionContext _localctx = new TransitionContext(Context, State);
		EnterRule(_localctx, 6, RULE_transition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			stateReference();
			State = 92;
			Match(ARROW);
			State = 93;
			stateReference();
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 94;
				Match(COLON);
				State = 95;
				transitionLabel();
				}
			}

			State = 98;
			Match(NEWLINE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StateDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StateReferenceContext stateReference() {
			return GetRuleContext<StateReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(GraphParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(GraphParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(GraphParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DiagramBodyContext diagramBody() {
			return GetRuleContext<DiagramBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(GraphParser.RBRACE, 0); }
		public StateDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stateDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterStateDeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitStateDeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStateDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StateDeclarationContext stateDeclaration() {
		StateDeclarationContext _localctx = new StateDeclarationContext(Context, State);
		EnterRule(_localctx, 8, RULE_stateDeclaration);
		try {
			State = 112;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INITIAL_STATE_NAME:
			case NAME_ALL_LOWERCASE:
			case NAME_ALL_UPPERCASE:
			case NAME_CAMELCASE:
			case NAME_UPPER_SNAKE_CASE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 100;
				stateReference();
				State = 101;
				Match(COLON);
				State = 102;
				assignment();
				State = 103;
				Match(NEWLINE);
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 2);
				{
				State = 105;
				Match(T__0);
				State = 106;
				stateReference();
				State = 107;
				Match(LBRACE);
				State = 108;
				diagramBody();
				State = 109;
				Match(RBRACE);
				State = 110;
				Match(NEWLINE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PseudostateDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PseudostateNameContext pseudostateName() {
			return GetRuleContext<PseudostateNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PSEUDOSTATE() { return GetToken(GraphParser.PSEUDOSTATE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(GraphParser.NEWLINE, 0); }
		public PseudostateDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pseudostateDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterPseudostateDeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitPseudostateDeclaration(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPseudostateDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PseudostateDeclarationContext pseudostateDeclaration() {
		PseudostateDeclarationContext _localctx = new PseudostateDeclarationContext(Context, State);
		EnterRule(_localctx, 10, RULE_pseudostateDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114;
			Match(T__0);
			State = 115;
			pseudostateName();
			State = 116;
			Match(PSEUDOSTATE);
			State = 117;
			Match(NEWLINE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PseudostateNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_CAMELCASE() { return GetToken(GraphParser.NAME_CAMELCASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_LOWERCASE() { return GetToken(GraphParser.NAME_ALL_LOWERCASE, 0); }
		public PseudostateNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pseudostateName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterPseudostateName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitPseudostateName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPseudostateName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PseudostateNameContext pseudostateName() {
		PseudostateNameContext _localctx = new PseudostateNameContext(Context, State);
		EnterRule(_localctx, 12, RULE_pseudostateName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_LOWERCASE || _la==NAME_CAMELCASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StateReferenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INITIAL_STATE_NAME() { return GetToken(GraphParser.INITIAL_STATE_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PseudostateNameContext pseudostateName() {
			return GetRuleContext<PseudostateNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StateNameContext stateName() {
			return GetRuleContext<StateNameContext>(0);
		}
		public StateReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stateReference; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterStateReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitStateReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStateReference(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StateReferenceContext stateReference() {
		StateReferenceContext _localctx = new StateReferenceContext(Context, State);
		EnterRule(_localctx, 14, RULE_stateReference);
		try {
			State = 124;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INITIAL_STATE_NAME:
				EnterOuterAlt(_localctx, 1);
				{
				State = 121;
				Match(INITIAL_STATE_NAME);
				}
				break;
			case NAME_ALL_LOWERCASE:
			case NAME_CAMELCASE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 122;
				pseudostateName();
				}
				break;
			case NAME_ALL_UPPERCASE:
			case NAME_UPPER_SNAKE_CASE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 123;
				stateName();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StateNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_UPPER_SNAKE_CASE() { return GetToken(GraphParser.NAME_UPPER_SNAKE_CASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_UPPERCASE() { return GetToken(GraphParser.NAME_ALL_UPPERCASE, 0); }
		public StateNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stateName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterStateName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitStateName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStateName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StateNameContext stateName() {
		StateNameContext _localctx = new StateNameContext(Context, State);
		EnterRule(_localctx, 16, RULE_stateName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_UPPERCASE || _la==NAME_UPPER_SNAKE_CASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TransitionLabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LabelTextContext labelText() {
			return GetRuleContext<LabelTextContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PriorityContext priority() {
			return GetRuleContext<PriorityContext>(0);
		}
		public TransitionLabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_transitionLabel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterTransitionLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitTransitionLabel(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTransitionLabel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TransitionLabelContext transitionLabel() {
		TransitionLabelContext _localctx = new TransitionLabelContext(Context, State);
		EnterRule(_localctx, 18, RULE_transitionLabel);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LBRACK) {
				{
				State = 128;
				priority();
				}
			}

			State = 131;
			labelText();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PriorityContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(GraphParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(GraphParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(GraphParser.RBRACK, 0); }
		public PriorityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_priority; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterPriority(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitPriority(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPriority(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PriorityContext priority() {
		PriorityContext _localctx = new PriorityContext(Context, State);
		EnterRule(_localctx, 20, RULE_priority);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			Match(LBRACK);
			State = 134;
			Match(INT);
			State = 135;
			Match(RBRACK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LabelTextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LabelTextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_labelText; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterLabelText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitLabelText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLabelText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LabelTextContext labelText() {
		LabelTextContext _localctx = new LabelTextContext(Context, State);
		EnterRule(_localctx, 22, RULE_labelText);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 4673058635780L) != 0)) {
				{
				State = 137;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(GraphParser.COMMENT, 0); }
		public CommentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterComment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitComment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommentContext comment() {
		CommentContext _localctx = new CommentContext(Context, State);
		EnterRule(_localctx, 24, RULE_comment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140;
			Match(COMMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermReferenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_PASCALCASE() { return GetToken(GraphParser.NAME_PASCALCASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_UPPERCASE() { return GetToken(GraphParser.NAME_ALL_UPPERCASE, 0); }
		public TermReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_termReference; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterTermReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitTermReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTermReference(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermReferenceContext termReference() {
		TermReferenceContext _localctx = new TermReferenceContext(Context, State);
		EnterRule(_localctx, 26, RULE_termReference);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_UPPERCASE || _la==NAME_PASCALCASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermReferenceContext termReference() {
			return GetRuleContext<TermReferenceContext>(0);
		}
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitAtom(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 28, RULE_atom);
		try {
			State = 150;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 144;
				Match(T__1);
				State = 145;
				expression();
				State = 146;
				Match(T__2);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 148;
				comparison();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 149;
				termReference();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableReferenceContext variableReference() {
			return GetRuleContext<VariableReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(GraphParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueReferenceContext valueReference() {
			return GetRuleContext<ValueReferenceContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 30, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152;
			variableReference();
			State = 153;
			Match(ASSIGN);
			State = 154;
			valueReference();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OrExprContext orExpr() {
			return GetRuleContext<OrExprContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 32, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			orExpr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AndExprContext[] andExpr() {
			return GetRuleContexts<AndExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AndExprContext andExpr(int i) {
			return GetRuleContext<AndExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OR() { return GetTokens(GraphParser.OR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR(int i) {
			return GetToken(GraphParser.OR, i);
		}
		public OrExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterOrExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitOrExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrExprContext orExpr() {
		OrExprContext _localctx = new OrExprContext(Context, State);
		EnterRule(_localctx, 34, RULE_orExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 158;
			andExpr();
			State = 163;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OR) {
				{
				{
				State = 159;
				Match(OR);
				State = 160;
				andExpr();
				}
				}
				State = 165;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AndExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotExprContext[] notExpr() {
			return GetRuleContexts<NotExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NotExprContext notExpr(int i) {
			return GetRuleContext<NotExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AND() { return GetTokens(GraphParser.AND); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND(int i) {
			return GetToken(GraphParser.AND, i);
		}
		public AndExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_andExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterAndExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitAndExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AndExprContext andExpr() {
		AndExprContext _localctx = new AndExprContext(Context, State);
		EnterRule(_localctx, 36, RULE_andExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166;
			notExpr();
			State = 171;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==AND) {
				{
				{
				State = 167;
				Match(AND);
				State = 168;
				notExpr();
				}
				}
				State = 173;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NotExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(GraphParser.NOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NotExprContext notExpr() {
			return GetRuleContext<NotExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public NotExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_notExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterNotExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitNotExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NotExprContext notExpr() {
		NotExprContext _localctx = new NotExprContext(Context, State);
		EnterRule(_localctx, 38, RULE_notExpr);
		try {
			State = 177;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NOT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 174;
				Match(NOT);
				State = 175;
				notExpr();
				}
				break;
			case T__1:
			case NAME_ALL_UPPERCASE:
			case NAME_PASCALCASE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 176;
				atom();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeoutExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOW() { return GetToken(GraphParser.NOW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GTE() { return GetToken(GraphParser.GTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VariableReferenceContext variableReference() {
			return GetRuleContext<VariableReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(GraphParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueReferenceContext valueReference() {
			return GetRuleContext<ValueReferenceContext>(0);
		}
		public TimeoutExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_timeoutExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterTimeoutExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitTimeoutExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimeoutExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TimeoutExpressionContext timeoutExpression() {
		TimeoutExpressionContext _localctx = new TimeoutExpressionContext(Context, State);
		EnterRule(_localctx, 40, RULE_timeoutExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179;
			Match(NOW);
			State = 180;
			Match(GTE);
			State = 181;
			variableReference();
			State = 184;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PLUS) {
				{
				State = 182;
				Match(PLUS);
				State = 183;
				valueReference();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QuantifierExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public QuantifierVariableNameContext quantifierVariableName() {
			return GetRuleContext<QuantifierVariableNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PropertyNameContext propertyName() {
			return GetRuleContext<PropertyNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableReferenceContext variableReference() {
			return GetRuleContext<VariableReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompOpContext compOp() {
			return GetRuleContext<CompOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueReferenceContext valueReference() {
			return GetRuleContext<ValueReferenceContext>(0);
		}
		public QuantifierExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_quantifierExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterQuantifierExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitQuantifierExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuantifierExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QuantifierExpressionContext quantifierExpression() {
		QuantifierExpressionContext _localctx = new QuantifierExpressionContext(Context, State);
		EnterRule(_localctx, 42, RULE_quantifierExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			_la = TokenStream.LA(1);
			if ( !(_la==T__3 || _la==T__4) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 187;
			Match(T__1);
			State = 188;
			quantifierVariableName();
			State = 189;
			Match(T__5);
			State = 190;
			propertyName();
			State = 191;
			Match(T__6);
			State = 192;
			variableReference();
			State = 193;
			compOp();
			State = 194;
			valueReference();
			State = 195;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComparisonContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableReferenceContext variableReference() {
			return GetRuleContext<VariableReferenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CompOpContext compOp() {
			return GetRuleContext<CompOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueReferenceContext valueReference() {
			return GetRuleContext<ValueReferenceContext>(0);
		}
		public ComparisonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparison; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterComparison(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitComparison(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparison(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparisonContext comparison() {
		ComparisonContext _localctx = new ComparisonContext(Context, State);
		EnterRule(_localctx, 44, RULE_comparison);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 197;
			variableReference();
			State = 198;
			compOp();
			State = 199;
			valueReference();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CompOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(GraphParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUAL() { return GetToken(GraphParser.NOTEQUAL, 0); }
		public CompOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterCompOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitCompOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompOpContext compOp() {
		CompOpContext _localctx = new CompOpContext(Context, State);
		EnterRule(_localctx, 46, RULE_compOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201;
			_la = TokenStream.LA(1);
			if ( !(_la==EQUAL || _la==NOTEQUAL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropertyNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(GraphParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_LOWER_SNAKE_CASE() { return GetToken(GraphParser.NAME_LOWER_SNAKE_CASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_LOWERCASE() { return GetToken(GraphParser.NAME_ALL_LOWERCASE, 0); }
		public PropertyNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_propertyName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterPropertyName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitPropertyName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPropertyName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PropertyNameContext propertyName() {
		PropertyNameContext _localctx = new PropertyNameContext(Context, State);
		EnterRule(_localctx, 48, RULE_propertyName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203;
			Match(AT);
			State = 204;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_LOWERCASE || _la==NAME_LOWER_SNAKE_CASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GraphOrInterfaceNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_PASCALCASE() { return GetToken(GraphParser.NAME_PASCALCASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_UPPERCASE() { return GetToken(GraphParser.NAME_ALL_UPPERCASE, 0); }
		public GraphOrInterfaceNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_graphOrInterfaceName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterGraphOrInterfaceName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitGraphOrInterfaceName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGraphOrInterfaceName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GraphOrInterfaceNameContext graphOrInterfaceName() {
		GraphOrInterfaceNameContext _localctx = new GraphOrInterfaceNameContext(Context, State);
		EnterRule(_localctx, 50, RULE_graphOrInterfaceName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_UPPERCASE || _la==NAME_PASCALCASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_PASCALCASE() { return GetToken(GraphParser.NAME_PASCALCASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_UPPERCASE() { return GetToken(GraphParser.NAME_ALL_UPPERCASE, 0); }
		public VariableNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterVariableName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitVariableName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableNameContext variableName() {
		VariableNameContext _localctx = new VariableNameContext(Context, State);
		EnterRule(_localctx, 52, RULE_variableName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 208;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_UPPERCASE || _la==NAME_PASCALCASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QuantifierVariableNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_CAMELCASE() { return GetToken(GraphParser.NAME_CAMELCASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_LOWERCASE() { return GetToken(GraphParser.NAME_ALL_LOWERCASE, 0); }
		public QuantifierVariableNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_quantifierVariableName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterQuantifierVariableName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitQuantifierVariableName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuantifierVariableName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QuantifierVariableNameContext quantifierVariableName() {
		QuantifierVariableNameContext _localctx = new QuantifierVariableNameContext(Context, State);
		EnterRule(_localctx, 54, RULE_quantifierVariableName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_LOWERCASE || _la==NAME_CAMELCASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableReferenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public GraphOrInterfaceNameContext graphOrInterfaceName() {
			return GetRuleContext<GraphOrInterfaceNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(GraphParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VariableNameContext variableName() {
			return GetRuleContext<VariableNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACK() { return GetToken(GraphParser.LBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACK() { return GetToken(GraphParser.RBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PropertyNameContext propertyName() {
			return GetRuleContext<PropertyNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QuantifierVariableNameContext quantifierVariableName() {
			return GetRuleContext<QuantifierVariableNameContext>(0);
		}
		public VariableReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableReference; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterVariableReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitVariableReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableReference(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableReferenceContext variableReference() {
		VariableReferenceContext _localctx = new VariableReferenceContext(Context, State);
		EnterRule(_localctx, 56, RULE_variableReference);
		int _la;
		try {
			State = 226;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 212;
				graphOrInterfaceName();
				State = 220;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LBRACK) {
					{
					State = 213;
					Match(LBRACK);
					State = 216;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case AT:
						{
						State = 214;
						propertyName();
						}
						break;
					case NAME_ALL_LOWERCASE:
					case NAME_CAMELCASE:
						{
						State = 215;
						quantifierVariableName();
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 218;
					Match(RBRACK);
					}
				}

				State = 222;
				Match(DOT);
				State = 223;
				variableName();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 225;
				variableName();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueReferenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedNameContext qualifiedName() {
			return GetRuleContext<QualifiedNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DurationLiteralContext durationLiteral() {
			return GetRuleContext<DurationLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PropertyNameContext propertyName() {
			return GetRuleContext<PropertyNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BooleanLiteralContext booleanLiteral() {
			return GetRuleContext<BooleanLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NoneLiteralContext noneLiteral() {
			return GetRuleContext<NoneLiteralContext>(0);
		}
		public ValueReferenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_valueReference; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterValueReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitValueReference(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValueReference(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueReferenceContext valueReference() {
		ValueReferenceContext _localctx = new ValueReferenceContext(Context, State);
		EnterRule(_localctx, 58, RULE_valueReference);
		try {
			State = 233;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NAME_ALL_UPPERCASE:
			case NAME_PASCALCASE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 228;
				qualifiedName();
				}
				break;
			case NOW:
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 229;
				durationLiteral();
				}
				break;
			case AT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 230;
				propertyName();
				}
				break;
			case T__7:
			case T__8:
				EnterOuterAlt(_localctx, 4);
				{
				State = 231;
				booleanLiteral();
				}
				break;
			case T__9:
				EnterOuterAlt(_localctx, 5);
				{
				State = 232;
				noneLiteral();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiedNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EnumerationTypeNameContext enumerationTypeName() {
			return GetRuleContext<EnumerationTypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DCOLON() { return GetToken(GraphParser.DCOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public EnumerationLiteralNameContext enumerationLiteralName() {
			return GetRuleContext<EnumerationLiteralNameContext>(0);
		}
		public QualifiedNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifiedName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterQualifiedName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitQualifiedName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQualifiedName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QualifiedNameContext qualifiedName() {
		QualifiedNameContext _localctx = new QualifiedNameContext(Context, State);
		EnterRule(_localctx, 60, RULE_qualifiedName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 235;
			enumerationTypeName();
			State = 236;
			Match(DCOLON);
			State = 237;
			enumerationLiteralName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DurationLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(GraphParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MILLISECONDS() { return GetToken(GraphParser.MILLISECONDS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOW() { return GetToken(GraphParser.NOW, 0); }
		public DurationLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_durationLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterDurationLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitDurationLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDurationLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DurationLiteralContext durationLiteral() {
		DurationLiteralContext _localctx = new DurationLiteralContext(Context, State);
		EnterRule(_localctx, 62, RULE_durationLiteral);
		try {
			State = 242;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 239;
				Match(NUMBER);
				State = 240;
				Match(MILLISECONDS);
				}
				break;
			case NOW:
				EnterOuterAlt(_localctx, 2);
				{
				State = 241;
				Match(NOW);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BooleanLiteralContext : ParserRuleContext {
		public BooleanLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_booleanLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterBooleanLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitBooleanLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBooleanLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BooleanLiteralContext booleanLiteral() {
		BooleanLiteralContext _localctx = new BooleanLiteralContext(Context, State);
		EnterRule(_localctx, 64, RULE_booleanLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 244;
			_la = TokenStream.LA(1);
			if ( !(_la==T__7 || _la==T__8) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NoneLiteralContext : ParserRuleContext {
		public NoneLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_noneLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterNoneLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitNoneLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNoneLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NoneLiteralContext noneLiteral() {
		NoneLiteralContext _localctx = new NoneLiteralContext(Context, State);
		EnterRule(_localctx, 66, RULE_noneLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 246;
			Match(T__9);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumerationTypeNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_PASCALCASE() { return GetToken(GraphParser.NAME_PASCALCASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_UPPERCASE() { return GetToken(GraphParser.NAME_ALL_UPPERCASE, 0); }
		public EnumerationTypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumerationTypeName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterEnumerationTypeName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitEnumerationTypeName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumerationTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumerationTypeNameContext enumerationTypeName() {
		EnumerationTypeNameContext _localctx = new EnumerationTypeNameContext(Context, State);
		EnterRule(_localctx, 68, RULE_enumerationTypeName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 248;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_UPPERCASE || _la==NAME_PASCALCASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumerationLiteralNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_UPPER_SNAKE_CASE() { return GetToken(GraphParser.NAME_UPPER_SNAKE_CASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME_ALL_UPPERCASE() { return GetToken(GraphParser.NAME_ALL_UPPERCASE, 0); }
		public EnumerationLiteralNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumerationLiteralName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.EnterEnumerationLiteralName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IGraphListener typedListener = listener as IGraphListener;
			if (typedListener != null) typedListener.ExitEnumerationLiteralName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGraphVisitor<TResult> typedVisitor = visitor as IGraphVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumerationLiteralName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumerationLiteralNameContext enumerationLiteralName() {
		EnumerationLiteralNameContext _localctx = new EnumerationLiteralNameContext(Context, State);
		EnterRule(_localctx, 70, RULE_enumerationLiteralName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250;
			_la = TokenStream.LA(1);
			if ( !(_la==NAME_ALL_UPPERCASE || _la==NAME_UPPER_SNAKE_CASE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,45,253,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,2,35,7,35,
		1,0,1,0,3,0,75,8,0,1,0,1,0,1,0,1,1,1,1,1,2,1,2,1,2,1,2,1,2,5,2,87,8,2,
		10,2,12,2,90,9,2,1,3,1,3,1,3,1,3,1,3,3,3,97,8,3,1,3,1,3,1,4,1,4,1,4,1,
		4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,113,8,4,1,5,1,5,1,5,1,5,1,5,1,6,
		1,6,1,7,1,7,1,7,3,7,125,8,7,1,8,1,8,1,9,3,9,130,8,9,1,9,1,9,1,10,1,10,
		1,10,1,10,1,11,3,11,139,8,11,1,12,1,12,1,13,1,13,1,14,1,14,1,14,1,14,1,
		14,1,14,3,14,151,8,14,1,15,1,15,1,15,1,15,1,16,1,16,1,17,1,17,1,17,5,17,
		162,8,17,10,17,12,17,165,9,17,1,18,1,18,1,18,5,18,170,8,18,10,18,12,18,
		173,9,18,1,19,1,19,1,19,3,19,178,8,19,1,20,1,20,1,20,1,20,1,20,3,20,185,
		8,20,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,22,1,22,
		1,22,1,22,1,23,1,23,1,24,1,24,1,24,1,25,1,25,1,26,1,26,1,27,1,27,1,28,
		1,28,1,28,1,28,3,28,217,8,28,1,28,1,28,3,28,221,8,28,1,28,1,28,1,28,1,
		28,3,28,227,8,28,1,29,1,29,1,29,1,29,1,29,3,29,234,8,29,1,30,1,30,1,30,
		1,30,1,31,1,31,1,31,3,31,243,8,31,1,32,1,32,1,33,1,33,1,34,1,34,1,35,1,
		35,1,35,0,0,36,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,0,7,2,0,37,37,40,40,2,
		0,38,38,41,41,2,0,38,38,42,42,1,0,4,5,1,0,28,29,2,0,37,37,39,39,1,0,8,
		9,242,0,72,1,0,0,0,2,79,1,0,0,0,4,88,1,0,0,0,6,91,1,0,0,0,8,112,1,0,0,
		0,10,114,1,0,0,0,12,119,1,0,0,0,14,124,1,0,0,0,16,126,1,0,0,0,18,129,1,
		0,0,0,20,133,1,0,0,0,22,138,1,0,0,0,24,140,1,0,0,0,26,142,1,0,0,0,28,150,
		1,0,0,0,30,152,1,0,0,0,32,156,1,0,0,0,34,158,1,0,0,0,36,166,1,0,0,0,38,
		177,1,0,0,0,40,179,1,0,0,0,42,186,1,0,0,0,44,197,1,0,0,0,46,201,1,0,0,
		0,48,203,1,0,0,0,50,206,1,0,0,0,52,208,1,0,0,0,54,210,1,0,0,0,56,226,1,
		0,0,0,58,233,1,0,0,0,60,235,1,0,0,0,62,242,1,0,0,0,64,244,1,0,0,0,66,246,
		1,0,0,0,68,248,1,0,0,0,70,250,1,0,0,0,72,74,5,11,0,0,73,75,3,2,1,0,74,
		73,1,0,0,0,74,75,1,0,0,0,75,76,1,0,0,0,76,77,3,4,2,0,77,78,5,12,0,0,78,
		1,1,0,0,0,79,80,3,50,25,0,80,3,1,0,0,0,81,87,3,6,3,0,82,87,3,8,4,0,83,
		87,3,10,5,0,84,87,3,24,12,0,85,87,5,22,0,0,86,81,1,0,0,0,86,82,1,0,0,0,
		86,83,1,0,0,0,86,84,1,0,0,0,86,85,1,0,0,0,87,90,1,0,0,0,88,86,1,0,0,0,
		88,89,1,0,0,0,89,5,1,0,0,0,90,88,1,0,0,0,91,92,3,14,7,0,92,93,5,13,0,0,
		93,96,3,14,7,0,94,95,5,14,0,0,95,97,3,18,9,0,96,94,1,0,0,0,96,97,1,0,0,
		0,97,98,1,0,0,0,98,99,5,22,0,0,99,7,1,0,0,0,100,101,3,14,7,0,101,102,5,
		14,0,0,102,103,3,30,15,0,103,104,5,22,0,0,104,113,1,0,0,0,105,106,5,1,
		0,0,106,107,3,14,7,0,107,108,5,17,0,0,108,109,3,4,2,0,109,110,5,18,0,0,
		110,111,5,22,0,0,111,113,1,0,0,0,112,100,1,0,0,0,112,105,1,0,0,0,113,9,
		1,0,0,0,114,115,5,1,0,0,115,116,3,12,6,0,116,117,5,24,0,0,117,118,5,22,
		0,0,118,11,1,0,0,0,119,120,7,0,0,0,120,13,1,0,0,0,121,125,5,19,0,0,122,
		125,3,12,6,0,123,125,3,16,8,0,124,121,1,0,0,0,124,122,1,0,0,0,124,123,
		1,0,0,0,125,15,1,0,0,0,126,127,7,1,0,0,127,17,1,0,0,0,128,130,3,20,10,
		0,129,128,1,0,0,0,129,130,1,0,0,0,130,131,1,0,0,0,131,132,3,22,11,0,132,
		19,1,0,0,0,133,134,5,15,0,0,134,135,5,20,0,0,135,136,5,16,0,0,136,21,1,
		0,0,0,137,139,3,32,16,0,138,137,1,0,0,0,138,139,1,0,0,0,139,23,1,0,0,0,
		140,141,5,21,0,0,141,25,1,0,0,0,142,143,7,2,0,0,143,27,1,0,0,0,144,145,
		5,2,0,0,145,146,3,32,16,0,146,147,5,3,0,0,147,151,1,0,0,0,148,151,3,44,
		22,0,149,151,3,26,13,0,150,144,1,0,0,0,150,148,1,0,0,0,150,149,1,0,0,0,
		151,29,1,0,0,0,152,153,3,56,28,0,153,154,5,44,0,0,154,155,3,58,29,0,155,
		31,1,0,0,0,156,157,3,34,17,0,157,33,1,0,0,0,158,163,3,36,18,0,159,160,
		5,26,0,0,160,162,3,36,18,0,161,159,1,0,0,0,162,165,1,0,0,0,163,161,1,0,
		0,0,163,164,1,0,0,0,164,35,1,0,0,0,165,163,1,0,0,0,166,171,3,38,19,0,167,
		168,5,25,0,0,168,170,3,38,19,0,169,167,1,0,0,0,170,173,1,0,0,0,171,169,
		1,0,0,0,171,172,1,0,0,0,172,37,1,0,0,0,173,171,1,0,0,0,174,175,5,27,0,
		0,175,178,3,38,19,0,176,178,3,28,14,0,177,174,1,0,0,0,177,176,1,0,0,0,
		178,39,1,0,0,0,179,180,5,33,0,0,180,181,5,35,0,0,181,184,3,56,28,0,182,
		183,5,36,0,0,183,185,3,58,29,0,184,182,1,0,0,0,184,185,1,0,0,0,185,41,
		1,0,0,0,186,187,7,3,0,0,187,188,5,2,0,0,188,189,3,54,27,0,189,190,5,6,
		0,0,190,191,3,48,24,0,191,192,5,7,0,0,192,193,3,56,28,0,193,194,3,46,23,
		0,194,195,3,58,29,0,195,196,5,3,0,0,196,43,1,0,0,0,197,198,3,56,28,0,198,
		199,3,46,23,0,199,200,3,58,29,0,200,45,1,0,0,0,201,202,7,4,0,0,202,47,
		1,0,0,0,203,204,5,32,0,0,204,205,7,5,0,0,205,49,1,0,0,0,206,207,7,2,0,
		0,207,51,1,0,0,0,208,209,7,2,0,0,209,53,1,0,0,0,210,211,7,0,0,0,211,55,
		1,0,0,0,212,220,3,50,25,0,213,216,5,15,0,0,214,217,3,48,24,0,215,217,3,
		54,27,0,216,214,1,0,0,0,216,215,1,0,0,0,217,218,1,0,0,0,218,219,5,16,0,
		0,219,221,1,0,0,0,220,213,1,0,0,0,220,221,1,0,0,0,221,222,1,0,0,0,222,
		223,5,30,0,0,223,224,3,52,26,0,224,227,1,0,0,0,225,227,3,52,26,0,226,212,
		1,0,0,0,226,225,1,0,0,0,227,57,1,0,0,0,228,234,3,60,30,0,229,234,3,62,
		31,0,230,234,3,48,24,0,231,234,3,64,32,0,232,234,3,66,33,0,233,228,1,0,
		0,0,233,229,1,0,0,0,233,230,1,0,0,0,233,231,1,0,0,0,233,232,1,0,0,0,234,
		59,1,0,0,0,235,236,3,68,34,0,236,237,5,31,0,0,237,238,3,70,35,0,238,61,
		1,0,0,0,239,240,5,43,0,0,240,243,5,34,0,0,241,243,5,33,0,0,242,239,1,0,
		0,0,242,241,1,0,0,0,243,63,1,0,0,0,244,245,7,6,0,0,245,65,1,0,0,0,246,
		247,5,10,0,0,247,67,1,0,0,0,248,249,7,2,0,0,249,69,1,0,0,0,250,251,7,1,
		0,0,251,71,1,0,0,0,18,74,86,88,96,112,124,129,138,150,163,171,177,184,
		216,220,226,233,242
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
