//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Graph.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGraphListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GraphBaseListener : IGraphListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.diagram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiagram([NotNull] GraphParser.DiagramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.diagram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiagram([NotNull] GraphParser.DiagramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.diagramName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiagramName([NotNull] GraphParser.DiagramNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.diagramName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiagramName([NotNull] GraphParser.DiagramNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.diagramBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiagramBody([NotNull] GraphParser.DiagramBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.diagramBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiagramBody([NotNull] GraphParser.DiagramBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.transition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransition([NotNull] GraphParser.TransitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.transition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransition([NotNull] GraphParser.TransitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.stateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateDeclaration([NotNull] GraphParser.StateDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.stateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateDeclaration([NotNull] GraphParser.StateDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.pseudostateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPseudostateDeclaration([NotNull] GraphParser.PseudostateDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.pseudostateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPseudostateDeclaration([NotNull] GraphParser.PseudostateDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.pseudostateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPseudostateName([NotNull] GraphParser.PseudostateNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.pseudostateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPseudostateName([NotNull] GraphParser.PseudostateNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.stateReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateReference([NotNull] GraphParser.StateReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.stateReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateReference([NotNull] GraphParser.StateReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.stateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateName([NotNull] GraphParser.StateNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.stateName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateName([NotNull] GraphParser.StateNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.transitionLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransitionLabel([NotNull] GraphParser.TransitionLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.transitionLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransitionLabel([NotNull] GraphParser.TransitionLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.priority"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPriority([NotNull] GraphParser.PriorityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.priority"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPriority([NotNull] GraphParser.PriorityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.labelText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelText([NotNull] GraphParser.LabelTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.labelText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelText([NotNull] GraphParser.LabelTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] GraphParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] GraphParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.termReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTermReference([NotNull] GraphParser.TermReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.termReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTermReference([NotNull] GraphParser.TermReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] GraphParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] GraphParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] GraphParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] GraphParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] GraphParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] GraphParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] GraphParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] GraphParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] GraphParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] GraphParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.notExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpr([NotNull] GraphParser.NotExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.notExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpr([NotNull] GraphParser.NotExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.timeoutExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimeoutExpression([NotNull] GraphParser.TimeoutExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.timeoutExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimeoutExpression([NotNull] GraphParser.TimeoutExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.quantifierExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantifierExpression([NotNull] GraphParser.QuantifierExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.quantifierExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantifierExpression([NotNull] GraphParser.QuantifierExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] GraphParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] GraphParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOp([NotNull] GraphParser.CompOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOp([NotNull] GraphParser.CompOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyName([NotNull] GraphParser.PropertyNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.propertyName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyName([NotNull] GraphParser.PropertyNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.graphOrInterfaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphOrInterfaceName([NotNull] GraphParser.GraphOrInterfaceNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.graphOrInterfaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphOrInterfaceName([NotNull] GraphParser.GraphOrInterfaceNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableName([NotNull] GraphParser.VariableNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableName([NotNull] GraphParser.VariableNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.quantifierVariableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuantifierVariableName([NotNull] GraphParser.QuantifierVariableNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.quantifierVariableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuantifierVariableName([NotNull] GraphParser.QuantifierVariableNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableReference([NotNull] GraphParser.VariableReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableReference([NotNull] GraphParser.VariableReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.valueReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueReference([NotNull] GraphParser.ValueReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.valueReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueReference([NotNull] GraphParser.ValueReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] GraphParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] GraphParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.durationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDurationLiteral([NotNull] GraphParser.DurationLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.durationLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDurationLiteral([NotNull] GraphParser.DurationLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteral([NotNull] GraphParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteral([NotNull] GraphParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.noneLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoneLiteral([NotNull] GraphParser.NoneLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.noneLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoneLiteral([NotNull] GraphParser.NoneLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.enumerationTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerationTypeName([NotNull] GraphParser.EnumerationTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.enumerationTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerationTypeName([NotNull] GraphParser.EnumerationTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.enumerationLiteralName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerationLiteralName([NotNull] GraphParser.EnumerationLiteralNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.enumerationLiteralName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerationLiteralName([NotNull] GraphParser.EnumerationLiteralNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
