//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Graph.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GraphParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGraphListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiagram([NotNull] GraphParser.DiagramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiagram([NotNull] GraphParser.DiagramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.diagramName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiagramName([NotNull] GraphParser.DiagramNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.diagramName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiagramName([NotNull] GraphParser.DiagramNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.diagramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiagramBody([NotNull] GraphParser.DiagramBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.diagramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiagramBody([NotNull] GraphParser.DiagramBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.transition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransition([NotNull] GraphParser.TransitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.transition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransition([NotNull] GraphParser.TransitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.stateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateDeclaration([NotNull] GraphParser.StateDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.stateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateDeclaration([NotNull] GraphParser.StateDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.pseudostateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPseudostateDeclaration([NotNull] GraphParser.PseudostateDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.pseudostateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPseudostateDeclaration([NotNull] GraphParser.PseudostateDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.pseudostateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPseudostateName([NotNull] GraphParser.PseudostateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.pseudostateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPseudostateName([NotNull] GraphParser.PseudostateNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.stateReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateReference([NotNull] GraphParser.StateReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.stateReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateReference([NotNull] GraphParser.StateReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateName([NotNull] GraphParser.StateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateName([NotNull] GraphParser.StateNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.transitionLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTransitionLabel([NotNull] GraphParser.TransitionLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.transitionLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTransitionLabel([NotNull] GraphParser.TransitionLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.priority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPriority([NotNull] GraphParser.PriorityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.priority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPriority([NotNull] GraphParser.PriorityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.labelText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelText([NotNull] GraphParser.LabelTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.labelText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelText([NotNull] GraphParser.LabelTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] GraphParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] GraphParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.termReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermReference([NotNull] GraphParser.TermReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.termReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermReference([NotNull] GraphParser.TermReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] GraphParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] GraphParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] GraphParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] GraphParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] GraphParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] GraphParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] GraphParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] GraphParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] GraphParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] GraphParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] GraphParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] GraphParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.timeoutExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimeoutExpression([NotNull] GraphParser.TimeoutExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.timeoutExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimeoutExpression([NotNull] GraphParser.TimeoutExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.quantifierExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantifierExpression([NotNull] GraphParser.QuantifierExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.quantifierExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantifierExpression([NotNull] GraphParser.QuantifierExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] GraphParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] GraphParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOp([NotNull] GraphParser.CompOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOp([NotNull] GraphParser.CompOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyName([NotNull] GraphParser.PropertyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyName([NotNull] GraphParser.PropertyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.graphOrInterfaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphOrInterfaceName([NotNull] GraphParser.GraphOrInterfaceNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.graphOrInterfaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphOrInterfaceName([NotNull] GraphParser.GraphOrInterfaceNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableName([NotNull] GraphParser.VariableNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableName([NotNull] GraphParser.VariableNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.quantifierVariableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuantifierVariableName([NotNull] GraphParser.QuantifierVariableNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.quantifierVariableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuantifierVariableName([NotNull] GraphParser.QuantifierVariableNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableReference([NotNull] GraphParser.VariableReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.variableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableReference([NotNull] GraphParser.VariableReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.valueReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueReference([NotNull] GraphParser.ValueReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.valueReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueReference([NotNull] GraphParser.ValueReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedName([NotNull] GraphParser.QualifiedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedName([NotNull] GraphParser.QualifiedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.durationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDurationLiteral([NotNull] GraphParser.DurationLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.durationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDurationLiteral([NotNull] GraphParser.DurationLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanLiteral([NotNull] GraphParser.BooleanLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanLiteral([NotNull] GraphParser.BooleanLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.noneLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoneLiteral([NotNull] GraphParser.NoneLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.noneLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoneLiteral([NotNull] GraphParser.NoneLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.enumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationTypeName([NotNull] GraphParser.EnumerationTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.enumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationTypeName([NotNull] GraphParser.EnumerationTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GraphParser.enumerationLiteralName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationLiteralName([NotNull] GraphParser.EnumerationLiteralNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GraphParser.enumerationLiteralName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationLiteralName([NotNull] GraphParser.EnumerationLiteralNameContext context);
}
