//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Graph.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GraphParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGraphVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiagram([NotNull] GraphParser.DiagramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.diagramName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiagramName([NotNull] GraphParser.DiagramNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.diagramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiagramBody([NotNull] GraphParser.DiagramBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.transition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransition([NotNull] GraphParser.TransitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.stateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateDecl([NotNull] GraphParser.StateDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.pseudostateDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudostateDecl([NotNull] GraphParser.PseudostateDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.pseudostateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudostateName([NotNull] GraphParser.PseudostateNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.stateRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateRef([NotNull] GraphParser.StateRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.stateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStateName([NotNull] GraphParser.StateNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.transitionLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransitionLabel([NotNull] GraphParser.TransitionLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.priority"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPriority([NotNull] GraphParser.PriorityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.labelText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelText([NotNull] GraphParser.LabelTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] GraphParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.termRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermRef([NotNull] GraphParser.TermRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] GraphParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] GraphParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GraphParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] GraphParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] GraphParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.notExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] GraphParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.timeoutExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeoutExpr([NotNull] GraphParser.TimeoutExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.quantifierExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantifierExpr([NotNull] GraphParser.QuantifierExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] GraphParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOp([NotNull] GraphParser.CompOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.propertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyName([NotNull] GraphParser.PropertyNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.graphOrInterfaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraphOrInterfaceName([NotNull] GraphParser.GraphOrInterfaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableName([NotNull] GraphParser.VariableNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.quantifierVariableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantifierVariableName([NotNull] GraphParser.QuantifierVariableNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.refVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefVar([NotNull] GraphParser.RefVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.valueReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueReference([NotNull] GraphParser.ValueReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] GraphParser.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.durationLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDurationLiteral([NotNull] GraphParser.DurationLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] GraphParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.noneLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoneLiteral([NotNull] GraphParser.NoneLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.enumerationTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationTypeName([NotNull] GraphParser.EnumerationTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GraphParser.enumerationLiteralName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationLiteralName([NotNull] GraphParser.EnumerationLiteralNameContext context);
}
