//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace FormalInterlocking.Model
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class InterfaceAssignment
    {
        [Newtonsoft.Json.JsonProperty("inputs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, InterfaceInputField> Inputs { get; set; }

        [Newtonsoft.Json.JsonProperty("outputs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, InterfaceOutputField> Outputs { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class InterfaceInputField
    {
        [Newtonsoft.Json.JsonProperty("description", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; }

        /// <summary>
        /// Default value for the input.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("default", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public DefaultValue Default { get; set; }

        /// <summary>
        /// The type of interface: 'discrete' or 'continuous'.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("kind", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public InterfaceInputFieldKind Kind { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class InterfaceOutputField
    {
        [Newtonsoft.Json.JsonProperty("description", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; }

        /// <summary>
        /// The type of interface: 'discrete' or 'continuous'.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("kind", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public InterfaceOutputFieldKind Kind { get; set; }

        /// <summary>
        /// Map from possible output values to expressions.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("mapping", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, string> Mapping { get; set; }

        /// <summary>
        /// Default value for the output.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("default", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public DefaultValue Default { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ConceptProperty
    {
        /// <summary>
        /// Description of the property.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("description", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        /// <summary>
        /// Type of the property (e.g., boolean, time, or name of a concept).
        /// </summary>
        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Type { get; set; }

        /// <summary>
        /// Minimum cardinality.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("min", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Cardinality Min { get; set; }

        /// <summary>
        /// Maximum cardinality.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("max", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Cardinality Max { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class EntityType
    {
        /// <summary>
        /// The name of the entity type.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        /// <summary>
        /// A description of the entity type.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("description", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; }

        /// <summary>
        /// Properties of the entity type.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, ConceptProperty> Properties { get; set; }

        /// <summary>
        /// Interface assignments for this entity type.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("interfaces", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, InterfaceAssignment> Interfaces { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum InterfaceInputFieldKind
    {

        [System.Runtime.Serialization.EnumMember(Value = @"discrete")]
        Discrete = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"continuous")]
        Continuous = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum InterfaceOutputFieldKind
    {

        [System.Runtime.Serialization.EnumMember(Value = @"discrete")]
        Discrete = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"continuous")]
        Continuous = 1,


    }
}